### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by marado** [msramalho/desarquivo#1]
Seria muito interessante que esta ferramenta tivesse uma licença de Software Livre.

**Comment by msramalho** [comment]
Olá @marado, obrigado pelo feedback. Já resolvi o problema, sendo que tive de limitar a Creative Commons por causa do âmbito em que o projeto foi desenvolvido (arquivo.pt).

**Comment by marado** [comment]
Olá! Obrigado por teres escolhido uma licença.

Não entendo, contudo, o quê no "âmbito do projecto" é que te levou a escolher uma licença não-livre (uma CC non-commercial)... O vencedor do prémio em 2019 tem uma licença livre (https://github.com/meuparlamento/react-native-app , GPL), mas pode ter havido uma qualquer alteração nas regras deste ano que eu não esteja a encontrar.

Podes por favor esclarecer? Obrigado!

**Comment by msramalho** [comment]
Olá @marado, obrigado pelo comentário que até me permite explicar melhor o porquê. Sendo que a única restrição do concurso é ser CC eu optei por escolher a non-commercial por, para já, não achar que deva existir em formato comercial. Naturalmente, se tiveres alguma ideia futura de como queres fazer isso, estou disponível a repensar e a ouvir o que tens em mente :)
