### ISSUE TITLE
Releases e executáveis para diferentes OS

### ISSUE THREAD

**Issue by Norin-Radd** [msramalho/desarquivo#4]
Olá!

Há algum executável para se instalar a aplicação em windows?

Parece-me uma boa ferramenta, não sei o que os jornalistas usam, talvez o zotero ou o mendeley. 

Um zotero com grafos parece-me bem (mas eu não percebo nada disto)... 

Mas pergunto pelo executável porque será mais fácil para implementar a utilização desta ferramenta premiada.

Cumprimentos e excelente trabalho!

**Comment by msramalho** [comment]
Olá @Norin-Radd, boa questão. De momento a ferramenta é totalmente alojada na web, o que traz vantagens e desvantagens. Contudo a aposta em algo web, por ser mais facilmente usado em qualquer OS, foi a opção incial mais óbvia. Portanto, não faz para já sentido pensarmos em fazer aplicações nativas, visto que seria mais interessante investir em novas features e capacidades de análise (isto numa reflexão sobre gestão de tempo).

Posto isto, convido-te a experimentar a versão online (idealmente num computador, de qualquer OS 😛) neste URL: 
### https://msramalho.github.io/desarquivo/
